#stage-1
FROM node:16-alpine As builder
WORKDIR /app
COPY package.json package-lock.json ./
COPY . .
RUN npm install
#stage-2
FROM node:16-alpine
WORKDIR /app
COPY --from=builder /app .
EXPOSE 3000
ENTRYPOINT ["npm","start"]
